# Generated by Django 4.0.5 on 2022-06-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BE', 'BE'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('MTech', 'MTech')], max_length=1000)),
                ('title', models.CharField(blank=True, max_length=5000, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publisher', models.CharField(blank=True, max_length=2000, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isbn', models.CharField(max_length=1000)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
