# Generated by Django 4.0.5 on 2022-06-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
    ]
