# Generated by Django 4.0.5 on 2022-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='department',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
